// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/28/2026, 1:24:36 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ADMIN/Appchat/apps/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ADMIN/Appchat/apps/frontend/app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ADMIN/Appchat/apps/frontend/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ADMIN/Appchat/apps/frontend/app/plugins/**/*.{js,ts,mjs}","C:/Users/ADMIN/Appchat/apps/frontend/app/composables/**/*.{js,ts,mjs}","C:/Users/ADMIN/Appchat/apps/frontend/app/utils/**/*.{js,ts,mjs}","C:/Users/ADMIN/Appchat/apps/frontend/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ADMIN/Appchat/apps/frontend/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ADMIN/Appchat/apps/frontend/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ADMIN/Appchat/apps/frontend/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;